### ISSUE TITLE
Support of Laravel 8

### ISSUE THREAD

**Issue by bernhardh** [pos-lifestyle/laravel-nova-date-range-filter#11]
Maybe just remove your laravel row in the `require` of your `composer.json`. Its not necessary I think.

**Comment by bernhardh** [comment]
See pull request #9

**Comment by ragingdave** [comment]
@schroedan Can you take a look into this as it's preventing this package from being used it seems for a decent chunk of people.

**Comment by schroedan** [comment]
Hi, sorry for the late reply. Will tag this as version `1.3.0`. Thank you for support.
