### ISSUE TITLE
Is that works with php8?

### ISSUE THREAD

**Issue by MWL91** [pos-lifestyle/laravel-nova-date-range-filter#15]
I supposed there is a typo in composer, ad php version should be `>=7.1` rather then `^7.1` - it dosn't work with php8 now :)

**Comment by MWL91** [comment]
https://github.com/pos-lifestyle/laravel-nova-date-range-filter/pull/16 i've fix that in my fork

**Comment by mattusik** [comment]
@schroedan May I ask you to merge #16 ?
